version: "3.9"

services:
  web:
    build: .
    container_name: <container_name>
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"